mod:animation:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/animation/**'

mod:app:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/app/**'

mod:asset:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/asset/**'

mod:audio:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/audio/**'

mod:color:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/color/**'

mod:command:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/command/**'

mod:core:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/core/**'

mod:datastructure:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/datastructures/**'

mod:device:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/device/**'

mod:diagnostic:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/diagnostic/**'

mod:ecs:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/ecs/**'

mod:emitter:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/emitter/**'

mod:event:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/event/**'

mod:geometry:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/geometry/**'

mod:gizmos:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/gizmo/**'

mod:hierarchy:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/hierarchy/**'

mod:input:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/input/**'
          - 'packages/input-core/**'
          - 'packages/keyboard/**'
          - 'packages/mouse/**'
          - 'packages/touch/**'

mod:logger:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/logger/**'

mod:math:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/math/**'

mod:misc:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/misc/**'

mod:movable:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/movable/**'

mod:name:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/name/**'

mod:noise:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/noise/**'

mod:physics:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/broadphase/**'
          - 'packages/damping/**'
          - 'packages/gravity/**'
          - 'packages/integrator/**'
          - 'packages/narrowphase/**'
          - 'packages/physics/**'

mod:profiler:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/profiler/**'

mod:reflect:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/reflect/**'

mod:relationship:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/relationship/**'

mod:render:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/render-canvas2d/**'
          - 'packages/render-core/**'
          - 'packages/render-webgl/**'

mod:scene:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/scene/**'

mod:schedule:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/schedule/**'

mod:storage:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/storage/**'

mod:time:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/time/**'

mod:transform:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/transform/**'

mod:tween:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/tween/**'

mod:type:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/type/**'

mod:utils:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/utils/**'

mod:window:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/window/**'
          - 'packages/window-dom/**'

scope:documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

scope:config:
  - changed-files:
      - any-glob-to-any-file:
          - '.config/**'
          - 'package.json'
          - 'package-lock.json'
          - 'tsconfig.json'

type:ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.husky/**'
