name: Feature request
description: Ask for a feature to be implemented.
labels: ["type:enhancement","rep:triage"]
body:
  - type: textarea
    id: genesis
    attributes:
      label: Genesis.
      description: |
        - Provide the reason that prompted the feature request.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description.
      description: |
        - Provide a description of the feature e.g how it works.
    validations:
      required: true
  - type: textarea
    id: solutions
    attributes:
      label: Solution(s).
      description: |
        - What methods can be used to implement the feature.
        - What are the advantages/disadvantages of each approach.
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: More information.
      description: |
        Provide more information such as:
         - related issues and prs.
         - what is needed before the feature can be added.
    validations:
      required: true
