name: Node.js Package

permissions:
  contents: read
  id-token: write
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - run: npm run check:release-version
      - run: npm run build

      - name: Publish workspaces to npm
        run: npx changeset publish
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Publish root package to npm
        run: npm publish --provenance
