name: Node.js Package

permissions:
  id-token: write
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Check version
        run: |
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$VERSION_TAG" != "$PACKAGE_VERSION" ]; then
            echo "Error: Git tag ($VERSION_TAG) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi
      - name: Publish check
        run: npm publish --dry-run

      - name: Publish to npm
        run: npm publish --provenance