name: Node.js Package

permissions:
  contents: read
  id-token: write
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Check version
        run: |
          VERSION_TAG="${GITHUB_REF_NAME#v}"
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$VERSION_TAG" != "$PACKAGE_VERSION" ]; then
            echo "Error: Git tag (${GITHUB_REF_NAME}) does not match package.json version (${PACKAGE_VERSION})"
            exit 1
          fi
      - name: Publish check
        run: npm publish --dry-run

      - name: Publish to npm
        run: npm publish --provenance
