name: CI

on:
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.filter.outputs.source }}
      examples: ${{ steps.filter.outputs.examples }}
      config: ${{ steps.filter.outputs.config }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          token: ''
          filters: |
            source:
              - 'src/**'
              - 'packages/**'
              - 'addons/**'
            examples:
              - 'examples/**'
            config:
              - '.config/**'
              - '.github/workflows/**'
              - 'package.json'
              - 'package-lock.json'
              - 'scripts/**'
              - 'turbo.json'
              - 'tsconfig.json'
  lint-source:
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' || needs.changes.outputs.config == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run lint:src-dry -- --max-warnings=0
  lint-examples:
    needs: changes
    if: ${{ needs.changes.outputs.examples == 'true' || needs.changes.outputs.config == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run lint:examples-dry -- --max-warnings=0
  tests:
    needs: compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test
  builds:
    needs: compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
  compiles:
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' || needs.changes.outputs.config == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run tsc:lint
